### ISSUE TITLE
Add application page

### ISSUE THREAD

**Issue by owlen** [paket-core/website#1]
Name: Application (MVP??)
Sections: 
 - What does it do (lower expections, but in an excited tone)
 - How to download
 - How to compile
 - how to run
- open issues
- how to help
- how to create your own

**Comment by israellevin** [comment]
https://docs.google.com/document/d/1ijHoynflkM63woHjb2x7yEJrKqqis8iqCrsKOqRM-l8/

**Comment by israellevin** [comment]
This is waiting for the actual application.
